import {Router} from 'express'; import multer from 'multer'; import crypto from 'node:crypto'; import {db} from '../db'; import {auth,AuthedRequest} from '../middleware/auth'; import {env} from '../config/env'; import {audit} from '../services/audit'; import {getFileAccess,getFolderAccess,listVisibleFolderIds} from '../services/access'; import {safeFilename} from '../utils/security'; import {activeSubscription} from '../middleware/subscription'; import {requireAddon} from '../services/entitlements'; import {putObject,getObject,deleteObject} from '../services/storage';
const r=Router(); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:env.MAX_UPLOAD_MB*1024*1024}});
function publicMeta(f:any){return {...f,sizeBytes:String(f.sizeBytes)}}
async function assertStorage(companyId:string,additional:number){const c=await db.company.findUnique({where:{id:companyId},select:{storageLimitGb:true,storageUsedBytes:true}});if(!c)throw new Error('Company not found');const limit=BigInt(Math.floor(c.storageLimitGb*1024*1024*1024));if(c.storageUsedBytes+BigInt(additional)>limit){const e=new Error('Storage limit exceeded');(e as any).status=413;throw e;}}
function key(){return crypto.randomUUID()}

r.get('/',auth,async(req:AuthedRequest,res,next)=>{try{const cid=req.user!.companyId;if(!cid)return res.status(400).json({error:'No company'});const q=String(req.query.q||'');const folderId=req.query.folderId?String(req.query.folderId):undefined;const sourceFilter=['UPLOAD','SCAN','FAX'].includes(String(req.query.source))?String(req.query.source):undefined;const visible=await listVisibleFolderIds(req.user!.id,req.user!.role,cid);if(folderId&&!await getFolderAccess(req.user!.id,req.user!.role,cid,folderId,'view'))return res.status(403).json({error:'Folder view permission denied'});const files=await db.file.findMany({where:{companyId:cid,name:{contains:q,mode:'insensitive'},...(sourceFilter?{source:sourceFilter as any}:{}),...(folderId?{folderId}:{OR:[{ownerId:req.user!.id},{folderId:{in:visible}}]})},orderBy:{createdAt:'desc'},take:100,include:{folder:{select:{id:true,name:true}}}});res.json(files.map(publicMeta));}catch(e){next(e)}});

async function saveUpload(reqFile:Express.Multer.File,keyName:string){await putObject(keyName,reqFile.buffer,reqFile.mimetype||'application/octet-stream');}

r.post('/upload',auth,activeSubscription,upload.single('file'),async(req:AuthedRequest,res,next)=>{try{if(!req.file||!req.user?.companyId)return res.status(400).json({error:'File and tenant required'});const cid=req.user.companyId;const folderId=req.body.folderId||undefined;if(folderId&&!await getFolderAccess(req.user.id,req.user.role,cid,folderId,'upload'))return res.status(403).json({error:'Upload permission denied'});await assertStorage(cid,req.file.size);const original=safeFilename(req.file.originalname);const storageKey=key();const checksum=crypto.createHash('sha256').update(req.file.buffer).digest('hex');await saveUpload(req.file,storageKey);try{const source=['UPLOAD','SCAN','FAX'].includes(String(req.body.source))?String(req.body.source):'UPLOAD';const f=await db.file.create({data:{companyId:cid,ownerId:req.user.id,folderId,name:original,storageKey,mimeType:req.file.mimetype,sizeBytes:req.file.size,checksum,source:source as any}});await db.company.update({where:{id:cid},data:{storageUsedBytes:{increment:req.file.size}}});await audit(cid,req.user.id,'UPLOAD','FILE',f.id);res.status(201).json(publicMeta(f));}catch(e){await deleteObject(storageKey);throw e;}}catch(e){next(e)}});

r.get('/:id',auth,async(req:AuthedRequest,res,next)=>{try{const f=await getFileAccess(req.user!.id,req.user!.role,req.user!.companyId!,String(req.params.id),'view');if(!f)return res.status(403).json({error:'View permission denied'});res.json(publicMeta(f));}catch(e){next(e)}});
r.get('/:id/download',auth,async(req:AuthedRequest,res,next)=>{try{const f=await getFileAccess(req.user!.id,req.user!.role,req.user!.companyId!,String(req.params.id),'download');if(!f)return res.status(403).json({error:'Download permission denied'});const data=await getObject(f.storageKey);if(!data)return res.status(404).json({error:'Stored file missing'});const safe=safeFilename(f.name);res.setHeader('Content-Type',f.mimeType||'application/octet-stream');res.setHeader('Content-Disposition',`attachment; filename="${safe.replace(/"/g,'')}"; filename*=UTF-8''${encodeURIComponent(f.name)}`);res.send(data);}catch(e){next(e)}});
r.get('/:id/preview',auth,async(req:AuthedRequest,res,next)=>{try{await requireAddon(req.user!.companyId!,'preview');const f=await getFileAccess(req.user!.id,req.user!.role,req.user!.companyId!,String(req.params.id),'view');if(!f)return res.status(403).json({error:'View permission denied'});const data=await getObject(f.storageKey);if(!data)return res.status(404).json({error:'Stored file missing'});res.type(f.mimeType||'application/octet-stream');res.send(data);}catch(e){next(e)}});
r.patch('/:id',auth,activeSubscription,async(req:AuthedRequest,res,next)=>{try{const f=await getFileAccess(req.user!.id,req.user!.role,req.user!.companyId!,String(req.params.id),'edit');if(!f)return res.status(403).json({error:'Edit permission denied'});const name=req.body.name?safeFilename(String(req.body.name)):f.name;const folderId=req.body.folderId===null?null:req.body.folderId||f.folderId;if(folderId&&!await getFolderAccess(req.user!.id,req.user!.role,req.user!.companyId!,folderId,'upload'))return res.status(403).json({error:'Folder permission denied'});res.json(publicMeta(await db.file.update({where:{id:f.id},data:{name,folderId}})));}catch(e){next(e)}});
r.delete('/:id',auth,activeSubscription,async(req:AuthedRequest,res,next)=>{try{const f=await getFileAccess(req.user!.id,req.user!.role,req.user!.companyId!,String(req.params.id),'delete');if(!f)return res.status(403).json({error:'Delete permission denied'});await deleteObject(f.storageKey);await db.file.delete({where:{id:f.id}});const c=await db.company.findUnique({where:{id:f.companyId},select:{storageUsedBytes:true}});const nextUsed=(c?.storageUsedBytes||0n)-f.sizeBytes;await db.company.update({where:{id:f.companyId},data:{storageUsedBytes:nextUsed<0n?0n:nextUsed}});await audit(f.companyId,req.user!.id,'DELETE','FILE',f.id);res.status(204).end();}catch(e){next(e)}});
r.post('/scan',auth,activeSubscription,upload.single('file'),async(req:AuthedRequest,res,next)=>{try{await requireAddon(req.user!.companyId!,'scanner');if(!req.file)return res.status(400).json({error:'PDF scan file required'});if(req.file.mimetype!=='application/pdf')return res.status(400).json({error:'Scanned document must be PDF'});const cid=req.user!.companyId!;await assertStorage(cid,req.file.size);const storageKey=`scan-${key()}`;await saveUpload(req.file,storageKey);const f=await db.file.create({data:{companyId:cid,ownerId:req.user!.id,name:safeFilename(req.file.originalname),storageKey,mimeType:'application/pdf',sizeBytes:req.file.size,source:'SCAN'}});await db.company.update({where:{id:cid},data:{storageUsedBytes:{increment:req.file.size}}});res.status(201).json(publicMeta(f));}catch(e){next(e)}});
r.post('/fax',auth,activeSubscription,upload.single('file'),async(req:AuthedRequest,res,next)=>{try{await requireAddon(req.user!.companyId!,'fax');if(!req.file)return res.status(400).json({error:'Fax document required'});const cid=req.user!.companyId!;await assertStorage(cid,req.file.size);const storageKey=`fax-${key()}`;await saveUpload(req.file,storageKey);const f=await db.file.create({data:{companyId:cid,ownerId:req.user!.id,name:safeFilename(req.file.originalname),storageKey,mimeType:req.file.mimetype,sizeBytes:req.file.size,source:'FAX'}});await db.company.update({where:{id:cid},data:{storageUsedBytes:{increment:req.file.size}}});res.status(201).json(publicMeta(f));}catch(e){next(e)}});
export default r;
