ALTER TABLE "Subscription" ADD COLUMN "stripeCustomerId" TEXT;
ALTER TABLE "Subscription" ADD COLUMN "stripeSubscriptionId" TEXT;
ALTER TABLE "Subscription" ADD COLUMN "billingInterval" TEXT;
ALTER TABLE "Subscription" ADD COLUMN "cancelAtPeriodEnd" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Subscription" ADD COLUMN "canceledAt" TIMESTAMP(3);
ALTER TABLE "Subscription" ADD COLUMN "pendingPlanCode" TEXT;
ALTER TABLE "Subscription" ADD COLUMN "pendingUsers" INTEGER;
ALTER TABLE "Subscription" ADD COLUMN "pendingStorageGb" DOUBLE PRECISION;
ALTER TABLE "Subscription" ADD COLUMN "pendingMonths" INTEGER;
ALTER TABLE "Subscription" ADD COLUMN "pendingPriceCents" INTEGER;
ALTER TABLE "Subscription" ADD COLUMN "pendingAddons" JSONB;
ALTER TABLE "Subscription" ADD COLUMN "pendingCheckoutId" TEXT;
CREATE INDEX "Subscription_stripeSubscriptionId_idx" ON "Subscription"("stripeSubscriptionId");
