import {Router} from 'express'; import {db} from '../db'; import {auth,AuthedRequest} from '../middleware/auth'; import {getFolderAccess,listVisibleFolderIds} from '../services/access'; import {safeFilename} from '../utils/security'; import {activeSubscription} from '../middleware/subscription';
const r=Router();

r.get('/',auth,async(req:AuthedRequest,res)=>{const cid=req.user?.companyId;if(!cid)return res.status(400).json({error:'No company'});const ids=await listVisibleFolderIds(req.user!.id,req.user!.role,cid);const where={companyId:cid,deletedAt:null,id:{in:ids}};res.json(await db.folder.findMany({where,orderBy:[{isPersonal:'desc'},{name:'asc'}]}));});

r.post('/',auth,activeSubscription,async(req:AuthedRequest,res)=>{if(!req.user?.companyId)return res.status(400).json({error:'No company'});const name=safeFilename(String(req.body.name||'New Folder'));const parentId=req.body.parentId||undefined;if(parentId&&!await getFolderAccess(req.user.id,req.user.role,req.user.companyId,parentId,'upload'))return res.status(403).json({error:'Folder permission denied'});res.status(201).json(await db.folder.create({data:{companyId:req.user.companyId,ownerId:req.user.id,parentId,name,isPersonal:false}}));});

r.patch('/:id',auth,activeSubscription,async(req:AuthedRequest,res,next)=>{try{const f=await getFolderAccess(req.user!.id,req.user!.role,req.user!.companyId!,String(req.params.id),'edit');if(!f)return res.status(403).json({error:'Edit permission denied'});if(f.isPersonal)return res.status(403).json({error:'Personal folders cannot be renamed or moved'});const parentId=req.body.parentId===null?null:req.body.parentId||f.parentId;if(parentId===f.id)return res.status(400).json({error:'Folder cannot contain itself'});if(parentId){const parent=await db.folder.findFirst({where:{id:parentId,companyId:f.companyId,deletedAt:null}});if(!parent)return res.status(404).json({error:'Destination folder not found'});let cursor:any=parent;while(cursor){if(cursor.id===f.id)return res.status(400).json({error:'A folder cannot be moved inside itself or one of its descendants'});cursor=cursor.parentId?await db.folder.findFirst({where:{id:cursor.parentId,companyId:f.companyId,deletedAt:null},select:{id:true,parentId:true}}):null;}if(!await getFolderAccess(req.user!.id,req.user!.role,req.user!.companyId!,parentId,'upload'))return res.status(403).json({error:'Destination folder permission denied'});}const updated=await db.folder.update({where:{id:f.id},data:{name:req.body.name?safeFilename(String(req.body.name)):f.name,parentId}});res.json(updated);}catch(e){next(e)}});

r.delete('/:id',auth,activeSubscription,async(req:AuthedRequest,res,next)=>{try{const f=await getFolderAccess(req.user!.id,req.user!.role,req.user!.companyId!,String(req.params.id),'delete');if(!f)return res.status(403).json({error:'Delete permission denied'});if(f.isPersonal)return res.status(403).json({error:'Personal folders cannot be deleted'});const now=new Date();const descendants=await db.folder.findMany({where:{companyId:f.companyId,deletedAt:null},select:{id:true,parentId:true}});const ids=new Set<string>([f.id]);let changed=true;while(changed){changed=false;for(const d of descendants){if(d.parentId&&ids.has(d.parentId)&&!ids.has(d.id)){ids.add(d.id);changed=true}}}await db.$transaction([db.folder.updateMany({where:{id:{in:[...ids]}},data:{deletedAt:now}}),db.file.updateMany({where:{companyId:f.companyId,folderId:{in:[...ids]},deletedAt:null},data:{deletedAt:now}})]);res.status(204).end();}catch(e){next(e)}});
export default r;
