import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import compression from 'compression'; import rateLimit from 'express-rate-limit';
import {env} from './config/env'; import {errors} from './middleware/error';
import auth from './routes/auth'; import companies from './routes/companies'; import users from './routes/users'; import files from './routes/files'; import folders from './routes/folders'; import sharing from './routes/sharing'; import workspace from './routes/workspace'; import subscriptions from './routes/subscriptions'; import superAdmin from './routes/superAdmin'; import publicRoutes from './routes/public'; import search from './routes/search'; import {subscriptionSweep} from './services/subscriptionWorker'; import integrations from './routes/integrations'; import {emailConfigured} from './services/email';
const app=express(); app.set('trust proxy',1);
app.set('json replacer', (_key: string, value: unknown) => typeof value === 'bigint' ? value.toString() : value);
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}})); app.use(compression());
const allowed=env.CORS_ORIGINS.split(',').map(x=>x.trim()).filter(Boolean); app.use(cors({exposedHeaders:['Content-Disposition'],origin:(origin,cb)=>{if(!origin||allowed.includes(origin)||env.NODE_ENV!=='production')return cb(null,true);cb(new Error('CORS blocked'));},credentials:true}));
app.use('/api/subscriptions/stripe-webhook',express.raw({type:'application/json',limit:'1mb'}));
app.use(express.json({limit:'2mb'})); app.use(express.urlencoded({extended:true,limit:'2mb'}));
app.use('/api/auth',rateLimit({windowMs:15*60*1000,max:100,standardHeaders:true,legacyHeaders:false}),auth);
app.use('/api/public',publicRoutes); app.use('/api/search',search); app.use('/api/companies',companies); app.use('/api/users',users); app.use('/api/files',files); app.use('/api/folders',folders); app.use('/api/sharing',sharing); app.use('/api/workspace',workspace); app.use('/api/subscriptions',subscriptions); app.use('/api/super-admin',superAdmin); app.use('/api/integrations',integrations);
app.get('/healthz',(_req,res)=>res.json({ok:true,emailConfigured:emailConfigured(),emailProvider:env.EMAIL_PROVIDER}));
app.use(errors);
app.listen(env.PORT,()=>console.log(`SecureFile API listening on ${env.PORT}`));
const runSweep=()=>subscriptionSweep().catch(console.error); runSweep(); setInterval(runSweep,60*60*1000);
