import { FormEvent, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { ArrowRight, Eye, EyeOff, KeyRound, ShieldCheck } from "lucide-react";
import AuthShell from "@/components/AuthShell";
import { api } from "@/lib/api";
import { connectSocket } from "@/services/socket";

export default function Login() {
  const nav = useNavigate(); const [sp] = useSearchParams();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [code,setCode]=useState(""); const [challenge,setChallenge]=useState(""); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [err,setErr]=useState("");
  const returnTo=sp.get("returnTo")||"";
  function finish(d:any){ localStorage.setItem("sf_token",d.token); localStorage.setItem("sf_email",d.user.email); localStorage.setItem("sf_display_name",d.user.name||d.user.email.split("@")[0]); localStorage.setItem("sf_user_id",d.user.id); localStorage.setItem("sf_role",d.user.role); localStorage.setItem("sf_addons",JSON.stringify(d.user.addons||{})); localStorage.setItem("sf_sidebar_items",JSON.stringify(d.user.sidebarItems||["files"])); localStorage.setItem("sf_plan",d.user.planCode||""); localStorage.setItem("sf_avatar_url",d.user.avatarUrl||""); connectSocket(d.token); nav(returnTo.startsWith("/")?returnTo:(d.user.role==="SUPER_ADMIN"?"/super-admin":"/dashboard")); }
  async function go(e:FormEvent){ e.preventDefault(); setErr(""); setBusy(true); try { if(challenge){ const d=await api("/auth/2fa/verify",{method:"POST",body:JSON.stringify({challengeToken:challenge,code})}); finish(d); } else { const d=await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})}); if(d.requiresTwoFactor){setChallenge(d.challengeToken);setCode("");} else finish(d); } } catch(e:any){setErr(e.message||"Unable to sign in.");} finally{setBusy(false);} }
  return <AuthShell title="Secure access, without the friction." subtitle="Sign in to your workspace and pick up exactly where you left off."><div className="auth-card-v2"><div className="auth-card-top"><span className="auth-icon-badge">{challenge?<ShieldCheck size={20}/>:<KeyRound size={20}/>}</span><div><p className="auth-eyebrow">SecureFile account</p><h2>{challenge?"Verify your identity":"Welcome back"}</h2><p>{challenge?"Enter the 6-digit code from your authenticator app.":"Sign in to your secure workspace."}</p></div></div>{err&&<div className="auth-error">{err}</div>}<form onSubmit={go}>{challenge?<label className="auth-field"><span>Authenticator code</span><input autoFocus inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000" className="auth-code-input"/><small>Open your authenticator app and enter the current 6-digit code.</small></label>:<><label className="auth-field"><span>Email address</span><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/></label><label className="auth-field"><span>Password</span><div className="auth-password-wrap"><input type={show?"text":"password"} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><small><Link to="/forgot-password">Forgot your password?</Link></small></label></>}<button className="auth-submit" disabled={busy||!!(challenge&&code.length!==6)} aria-busy={busy}>{busy?(challenge?"Verifying…":"Signing in…"):(challenge?"Verify & continue":"Sign in")}<ArrowRight size={17}/></button></form>{challenge&&<button className="auth-back-link" onClick={()=>setChallenge("")}>Use a different account</button>} {!challenge&&<div className="auth-footer-links"><span>New to SecureFile?</span><Link to="/signup">Create a workspace</Link></div>}</div></AuthShell>;
}
