import{useMemo,useState}from'react';import{Link,useNavigate}from'react-router-dom';
const ADDONS=[['preview','File Side-panel Preview',5],['scanner','Scanner',5],['fax','Fax',5],['reshare','File/Folder Re-sharing',1],['rename','User File Rename',2],['postal','Post-office Mailing',10]] as const;
export default function Pricing(){
 const nav=useNavigate();const[users,setUsers]=useState(1),[gb,setGb]=useState(10),[months,setMonths]=useState(1),[addons,setAddons]=useState<Record<string,boolean>>({});
 const q=useMemo(()=>{const user=10+Math.max(0,users-1)*5;const storage=gb*.3;const add=ADDONS.reduce((s,[k,,p])=>s+(addons[k]?p*users:0),0);const monthly=user+storage+add;return{monthly,total:monthly*months}},[users,gb,months,addons]);
 const query=new URLSearchParams({users:String(users),gb:String(gb),months:String(months),addons:JSON.stringify(addons)}).toString();
 return <div className="public"><div className="nav"><b>SecureFile</b><div><Link to="/">Home</Link><Link to="/login">Login</Link><Link className="btn small" to="/signup">Sign Up</Link></div></div>
 <div className="pricing"><div><p className="eyebrow">SecureFile SaaS</p><h1>Build your workspace.</h1><p>Choose users, storage, add-ons and subscription duration. One user is the Company Admin.</p><div className="panel"><h3>Latest pricing</h3><p>$10 first/base user/month · $5 each additional user/month · $0.30/GB/month</p>{ADDONS.map(([k,n,p])=><p key={k}>• {n}: ${p}/user/month</p>)}</div></div>
 <div className="price-card"><label>Users <b>{users}</b></label><input type="number" min="1" max="10000" value={users} onChange={e=>setUsers(Math.max(1,+e.target.value))}/><label>Storage (GB) <b>{gb}</b></label><input type="number" min="1" value={gb} onChange={e=>setGb(Math.max(1,+e.target.value))}/><label>Months</label><select value={months} onChange={e=>setMonths(+e.target.value)}>{[1,3,6,12,24,36].map(m=><option key={m} value={m}>{m} month{m>1?'s':''}</option>)}</select><h3>Add-ons</h3>{ADDONS.map(([k,n,p])=><label className="check" key={k}><input type="checkbox" checked={!!addons[k]} onChange={e=>setAddons({...addons,[k]:e.target.checked})}/>{n} — ${p}/user/month</label>)}<div className="price">${q.monthly.toFixed(2)} <small>/month</small></div><div className="muted">${q.total.toFixed(2)} total for {months} month{months>1?'s':''}</div><button className="btn" onClick={()=>nav(`/signup?${query}`)}>Continue</button></div></div></div>
}