function u16(b: Uint8Array, i: number){ return (b[i] << 8) | b[i+1]; }
function jpegSize(buf: Uint8Array){let i=2;while(i+9<buf.length){if(buf[i]!==0xff){i++;continue;}const marker=buf[i+1];i+=2;if(marker===0xd8||marker===0xd9)continue;if(marker===0xda)break;if(i+2>buf.length)break;const len=u16(buf,i);if(len<2||i+len>buf.length)break;const sof=(marker>=0xc0&&marker<=0xc3)||(marker>=0xc5&&marker<=0xc7)||(marker>=0xc9&&marker<=0xcb)||(marker>=0xcd&&marker<=0xcf);if(sof)return{height:u16(buf,i+3),width:u16(buf,i+5),components:buf[i+7]};i+=len;}throw new Error('Could not read JPEG dimensions.');}
const enc=new TextEncoder();const bytes=(s:string)=>enc.encode(s);const join=(parts:Uint8Array[])=>{const total=parts.reduce((n,p)=>n+p.length,0);const out=new Uint8Array(total);let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;};
export function jpegPagesToPdfBlob(pages:{data:string;mimeType?:string}[]){
 if(!pages.length)throw new Error('At least one scanned page is required.');
 const objects:Uint8Array[]=[];const add=(data:Uint8Array|string)=>{objects.push(typeof data==='string'?bytes(data):data);return objects.length;};const pagesId=add('');const pageIds:number[]=[];
 for(let index=0;index<pages.length;index++){const binary=atob(pages[index].data);const image=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)image[i]=binary.charCodeAt(i);if(image.length<4||image[0]!==0xff||image[1]!==0xd8)throw new Error(`Page ${index+1} is not a JPEG image.`);const{width,height,components}=jpegSize(image);const colorSpace=components===1?'/DeviceGray':components===4?'/DeviceCMYK':'/DeviceRGB';const imageHeader=bytes(`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace ${colorSpace} /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`);const imageId=add(join([imageHeader,image,bytes('\nendstream')]));const maxW=540,maxH=720,scale=Math.min(maxW/width,maxH/height),w=Math.max(1,width*scale),h=Math.max(1,height*scale),x=(612-w)/2,y=(792-h)/2;const content=`q\n${w.toFixed(2)} 0 0 ${h.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm\n/Im${index+1} Do\nQ\n`;const contentId=add(`<< /Length ${bytes(content).length} >>\nstream\n${content}endstream`);const pageId=add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /XObject << /Im${index+1} ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`);pageIds.push(pageId);}
 objects[pagesId-1]=bytes(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`);const catalogId=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);const header=bytes('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n');const chunks:Uint8Array[]=[header];const offsets=[0];let offset=header.length;for(let i=0;i<objects.length;i++){offsets.push(offset);const h=bytes(`${i+1} 0 obj\n`),t=bytes('\nendobj\n');chunks.push(h,objects[i],t);offset+=h.length+objects[i].length+t.length;}const xrefOffset=offset;let xref=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objects.length;i++)xref+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;xref+=`trailer\n<< /Size ${objects.length+1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;chunks.push(bytes(xref));return new Blob([join(chunks)],{type:'application/pdf'});
}
